apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.5.2
          env:
            - name: GF_SERVER_ROOT_URL
              value: http://localhost
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: secret
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP

