version: '3'
services:
  server:
    image: "rancher/k3s:v1.0.0"
    command: [server, --no-deploy, traefik]
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_TOKEN=jkpr392pjklmfdsa
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - K3S_NODE_NAME=master
    volumes:
      - .:/output
    ports:
      - 6443:6443
  agent:
    image: "rancher/k3s:v1.0.0"
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_URL=https://server:6443
      - K3S_TOKEN=jkpr392pjklmfdsa
      - K3S_NODE_NAME=node
