apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - "*"
    resources:
      - "*"
