apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  prometheus.yaml: |
    {{ .Files.Get "files/prometheus.yaml" | nindent 4}}
