apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: prometheus
          image: prom/prometheus:v2.14.0
          args:
            - --config.file=/etc/prometheus/config/prometheus.yaml
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
            initialDelaySeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: http
              path: /-/ready
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
