apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adapter.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.adapter.name }}
spec:
  selector:
    app: {{ .Values.adapter.name }}
  ports:
    - name: http
      port: {{ .Values.adapter.port }}
      protocol: TCP
