apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: timescaledb
          image: timescale/pg_prometheus:0.2.2-pg11
          args:
            - "-csynchronous_commit=off"
          ports:
            - containerPort: {{ .Values.postgres.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: secret
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
        namespace: {{ .Values.global.namespace }}
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
