global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    datacenter: localhost
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
remote_write:
  - url: "http://prom-pg-adapter:9201/write"
remote_read:
  - url: "http://prom-pg-adapter:9201/read"
